insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (3,'Energy pistol','weapon',25,5,10,'n','e');
insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (10,'Energy rifle ','weapon',25,10,3,'n','e');
insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (2,'Energy pack ','ammo',15,1,1,'y','p');
insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (4,'Flechette pistol','weapon',25,7,10,'n','p');
insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (10,'Flechette shotgun','weapon',50,7,3,'n','p');
insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (1,'Flechette cartridge','ammo',15,1,1,'y','p');
insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (3,'Axe','weapon',25,5,1,'n','p');
insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (1,'Switchblade','weapon',25,3,1,'n','p');
insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (3,'Sword','weapon',25,6,1,'n','p');
insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (3,'Personal shield','armor',5,3,1,'y','p');
insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (15,'Riot armor','armor',5,3,1,'n','p');
insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (1,'Vodka','booze',15,1,1,'y','p');
insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (1,'Spiced Rum','booze',15,1,1,'y','p');
insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (1,'Swill','booze',15,1,1,'y','p');
insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (1,'Whiskey','booze',15,1,1,'y','p');
insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (1,'Peach Schnapps','booze',15,1,1,'y','p');
insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (1,'White lightning','booze',15,1,1,'y','p');
insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (1,'PDA','tool',15,1,1,'y','p');
insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (1,'MRE','food',15,1,1,'y','p');
insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (1,'Desiccated meat','food',15,1,1,'y','p');
insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (1,'Desiccated vegetables','food',15,1,1,'y','p');
insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (1,'Canned goods','food',15,1,1,'y','p');
insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (2,'Torch cutter','tool',15,3,1,'n','p');
insert into itemtype (weight,name,type,accuracy,damage,capacity,consumable,damagetype) values (1,'Gas cartridge','ammo',15,1,1,'n','p');
