/*
 *  Copyright 2010 Jeffrey Hoyt.  All rights reserved.
 */
package invasion.dataobjects;

import java.util.logging.Level;
import java.util.logging.Logger;
import invasion.util.*;

import java.util.*;
import java.sql.*;

/**
 * Skill generated by hbm2java
 */
public class Skill implements java.io.Serializable
{

    public final static String KEY = Skill.class.getName();
    public final static Logger log = Logger.getLogger( KEY );

    //{{{ Members
    private int id;
    private String name;
    protected long value = 0;
    protected String race = null;
    protected int prereq = 0;  //the id of the prerequisite skill. 0 if there are none.
	protected int cost = 0;
    protected List<Skill> children = new ArrayList<Skill>();
    public static final String FIREARMS1 = "Firearms 1";
    public static final String FIREARMS2 = "Firearms 2";
    public static final String FIREARMS3 = "Firearms 3";
    public static final String FIREARMS4 = "Firearms 4";
    public static final String FIREARMS5 = "Firearms 5";
    public static final String TINKERER1 = "Tinkerer 1";
    public static final String TINKERER2 = "Tinkerer 2";
    public static final String TINKERER3 = "Tinkerer 3";
    public static final String TINKERER4 = "Tinkerer 4";
    public static final String TINKERER5 = "Tinkerer 5";
    public static final String MELEE1 = "Melee 1";
    public static final String MELEE2 = "Melee 2";
    public static final String MELEE3 = "Melee 3";
    public static final String MELEE4 = "Melee 4";
    public static final String MELEE5 = "Melee 5";
    public static final String HACKER1 = "Hacker 1";
    public static final String HACKER2 = "Hacker 2";
    public static final String HACKER3 = "Hacker 3";
    public static final String HACKER4 = "Hacker 4";
    public static final String HACKER5 = "Hacker 5";
    public static final String MEDIC1 = "Medic 1";
    public static final String MEDIC2 = "Medic 2";
    public static final String DOUBLE_SHOT = "Double Shot";
    public static final String KILL_SHOT = "Kill Shot";
    public static final String GOLIATH = "Goliath";
    public static final String WHIRLWIND = "Whirlwind";
    public static final String BRUTALITY = "Brutality";
    public static final String BODY1 = "Body Warp 1";
    public static final String BODY2 = "Body Warp 2";
    public static final String BODY3 = "Body Warp 3";
    public static final String BODY4 = "Body Warp 4";
    public static final String BODY5 = "Body Warp 5";
    public static final String SHARER1 = "Soul Sharer 1";
    public static final String SHARER2 = "Soul Sharer 2";
    public static final String SHARER3 = "Soul Sharer 3";
    public static final String SHARER4 = "Soul Sharer 4";
    public static final String SHARER5 = "Soul Sharer 5";
    public static final String PROTECTOR1 = "Protector of the Nest 1";
    public static final String PROTECTOR2 = "Protector of the Nest 2";
    public static final String PROTECTOR3 = "Protector of the Nest 3";
    public static final String PROTECTOR4 = "Protector of the Nest 4";
    public static final String PROTECTOR5 = "Protector of the Nest 5";
    public static final String TK1 = "Telekinesis 1";
    public static final String TK2 = "Telekinesis 2";
    public static final String TK3 = "Telekinesis 3";
    public static final String TK4 = "Telekinesis 4";
    public static final String TK5 = "Telekinesis 5";
    public static final String SUMMONER1 = "Summoner 1";
    public static final String SUMMONER2 = "Summoner 2";
    public static final String SUMMONER3 = "Summoner 3";
    public static final String SUMMONER4 = "Summoner 4";
    public static final String SUMMONER5 = "Summoner 5";
    public static final String TP1 = "Telepathy 1";
    public static final String TP2 = "Telepathy 2";
    public static final String TP3 = "Telepathy 3";
    public static final String TP4 = "Telepathy 4";
    public static final String TP5 = "Telepathy 5";
    protected String helplink = null;
    //}}}

    //{{{ Constuctors
    //}}}

    //{{{ Methods
    public void addChild(Skill s)
    {
        children.add(s);
    }
    //}}}

    //{{{ Getters and Setters
    public long getValue() { return this.value; }
    public void setValue(long value) { this.value = value; }
    public String getRace() { return this.race; }
    public void setRace(String race) { this.race = race; }
    public int getPrereq() { return this.prereq; }
    public void setPrereq(int prereq) { this.prereq = prereq; }
    public int getId() {return this.id;}
    public void setId(int id) {this.id = id;}
    public String getName() {return this.name;}
    public List<Skill> getChildren() { return this.children; }
    public void setChildren(List<Skill> children) { this.children = children; }
    public void setName(String name) {this.name = name;}
    public int getCost() { return this.cost; }
	public void setCost(int cost) { this.cost = cost; }
    public String getHelplink() { return this.helplink; }
	public void setHelplink(String helplink) { this.helplink = helplink; }
	    //}}}
}

// :wrap=none:noTabs=true:collapseFolds=1:folding=explicit:


