/*
 *  Copyright 2010 Jeffrey Hoyt.  All rights reserved.
 */
package invasion.dataobjects;

import java.util.logging.Level;
import java.util.logging.Logger;
import invasion.util.*;

import java.util.*;
import java.sql.*;

/**
 * Skill generated by hbm2java
 */
public class Skill implements java.io.Serializable
{

    public final static String KEY = Skill.class.getName();
    public final static Logger log = Logger.getLogger( KEY );
    // static{log.setLevel(Level.FINER);}

    //{{{ Members
    private int id;
    private String name;
    protected long value = 0;
    protected String race = null;
    protected int prereq = 0;  //the id of the prerequisite skill. 0 if there are none.
	protected int cost = 0;
    protected List<Skill> children = new ArrayList<Skill>();
    public final static String HUMAN = "human";
    public final static String PSI = "psi";
    public final static String MUTATE = "mutate";
    public final static String FIREARMS1 = "Firearms 1";
    public final static String FIREARMS2 = "Firearms 2";
    public final static String FIREARMS3 = "Firearms 3";
    public final static String FIREARMS4 = "Firearms 4";
    public final static String FIREARMS5 = "Firearms 5";
    public final static String TINKERER1 = "Tinkerer 1";
    public final static String TINKERER2 = "Tinkerer 2";
    public final static String TINKERER3 = "Tinkerer 3";
    public final static String TINKERER4 = "Tinkerer 4";
    public final static String TINKERER5 = "Tinkerer 5";
    public final static String MELEE1 = "Melee 1";
    public final static String MELEE2 = "Melee 2";
    public final static String MELEE3 = "Melee 3";
    public final static String MELEE4 = "Melee 4";
    public final static String MELEE5 = "Melee 5";
    public final static String HACKER1 = "Hacker 1";
    public final static String HACKER2 = "Hacker 2";
    public final static String HACKER3 = "Hacker 3";
    public final static String HACKER4 = "Hacker 4";
    public final static String HACKER5 = "Hacker 5";
    public final static String MEDIC1 = "Medic 1";
    public final static String MEDIC2 = "Medic 2";

    public final static String DOUBLE_SHOT = "Double Shot";
    public final static String KILL_SHOT = "Kill Shot";

    public final static String GOLIATH = "Goliath";
    public final static String WHIRLWIND = "Whirlwind";
    public final static String BRUTALITY = "Brutality";
	protected String helplink = null;
    //}}}

    //{{{ Constuctors
    //}}}

    //{{{ Methods
    public void addChild(Skill s)
    {
        children.add(s);
    }
    //}}}

    //{{{ Getters and Setters
    public long getValue() { return this.value; }
    public void setValue(long value) { this.value = value; }
    public String getRace() { return this.race; }
    public void setRace(String race) { this.race = race; }
    public int getPrereq() { return this.prereq; }
    public void setPrereq(int prereq) { this.prereq = prereq; }
    public int getId() {return this.id;}
    public void setId(int id) {this.id = id;}
    public String getName() {return this.name;}
    public List<Skill> getChildren() { return this.children; }
    public void setChildren(List<Skill> children) { this.children = children; }
    public void setName(String name) {this.name = name;}
    public int getCost() { return this.cost; }
	public void setCost(int cost) { this.cost = cost; }
    public String getHelplink() { return this.helplink; }
	public void setHelplink(String helplink) { this.helplink = helplink; }
	    //}}}
}

// :wrap=none:noTabs=true:collapseFolds=1:folding=explicit:


