/*
 *  Copyright 2010 Jeffrey Hoyt.  All rights reserved.
 */
package invasion.dataobjects;
// Generated Oct 20, 2009 4:47:37 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Skill generated by hbm2java
 */
public class Skill  implements java.io.Serializable {


     private int id;
     private String name;
     private Integer maxlevel;
     private Set<Alt> alts = new HashSet<Alt>(0);

    public Skill() {
    }


    public Skill(int id) {
        this.id = id;
    }
    public Skill(int id, String name, Integer maxlevel, Set<Alt> alts) {
       this.id = id;
       this.name = name;
       this.maxlevel = maxlevel;
       this.alts = alts;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
    public Integer getMaxlevel() {
        return this.maxlevel;
    }

    public void setMaxlevel(Integer maxlevel) {
        this.maxlevel = maxlevel;
    }
    public Set<Alt> getAlts() {
        return this.alts;
    }

    public void setAlts(Set<Alt> alts) {
        this.alts = alts;
    }




}


